import { Inter } from "next/font/google";
import Navbar from "./_components/Navbar";
import Sidebar from "./_components/Sidebar";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className="">
          <div className="flex">
            <Sidebar />
            <Navbar />
            <div className="flex-1 md:ml-64 p-4 mt-16">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
